---
default:
  proxy_server:
    enable: false
    host: 10.10.16.200
    port: 3128
  interval: 30
  node_exporter:
    prom_dir: 
      - /var/lib/node_exporter/textfile_collector
      - /textfile_collector

sensor:
  ceph:
    enable: true
    interval: 30
    cluster: ceph
    command: /usr/bin/ceph
    scripts:
      - ceph.py
      
  s3:
    enable: false
    provider:
      hcm04:
        - public:
          enable: true
          interval: 30
          request: 1
          profile: lab
          encryption: false
          profile: lab
          method:
            - head
            - download
            - upload
            - delete
          bucket:
            - data
          local_src:
            - /etc/hosts
          local_dst: 
            - /tmp/hosts
          endpoints:
            - https://hcm04.vstorage.vngcloud.vn
        - private:
          enable: true
          interval: 30
          request: 1
          profile: lab
          encryption: false
          method:
            - head
            - download
            - upload
            - delete
          bucket:
            - data
          local_src:
            - /etc/hosts
          local_dst: 
            - /tmp/hosts
          endpoints:
            - http://192.168.100.161:8020
            - http://192.168.100.162:8020
            - http://192.168.100.163:8020
    scripts:
      - s3.py

  common:
    enable: true
    interval: 30
    service_status:
      enable: true
      targets:
        - zabbix_agentd
        - auditbeat
        - podman
        - chronyd
    nf_conntrack:
      enable: true
    keepalived:
      enable: false
    scripts:
      - common.py

  podman:
    enable: true
    interval: 30
    scripts:
      - podman.py

  ceph_orch:
    enable: true
    interval: 30
    cluster: ceph
    command: /usr/bin/ceph
    scripts:
      - ceph_orch.py

  ceph_rgw:
    enable: false
    interval: 60
    cluster: ceph
    max_workers: 8
    limit_bucket: 10000
    reshard_threshold: 200000
    scripts:
      - ceph_rgw.py

sensor:
  audit:
    enable: true
    interval: 30
    scripts:
      - audit.py

    file_stats:
      enable: true
      files:
        - /etc/hosts
        - /etc/netplan/*.yaml
      folders:
        - /etc/nginx/*.conf

    command_detect:
      enable: true
      logs:
        - /var/log/syslog
      exclude_users:
        - ubuntu
      keywords_to_monitor:
        - rm -rf
        - systemctl restart
        - systemctl stop
        - systemctl disable
        - halt
        - kill -9
        - pkill -9
        - killall -9
        - docker stop
        - docker restart
        - docker rm
        - docker kill
        - docker image rm
        - docker container rm
        - docker volume rm
        - docker network rm
        - hostnamectl set-hostname
        - netplan apply
        - ssh
        - tail -f