---
default:
  proxy_server:
    enable: false
    host: 10.10.16.200
    port: 3128
  interval: 30
  node_exporter:
    prom_dir: 
      - /var/lib/node_exporter/textfile_collector1

sensor:
  ceph:
    enable: false
    interval: 30
    cluster: ceph
    command: /usr/bin/ceph
    scripts:
      - ceph.py
      
  common:
    enable: false
    interval: 30
    service_status:
      enable: true
      targets:
        - zabbix_agentd
        - auditbeat
        - podman
        - chronyd
    nf_conntrack:
      enable: true
    keepalived:
      enable: false
    scripts:
      - common.py

  podman:
    enable: false
    interval: 30
    scripts:
      - podman.py

  ceph_orch:
    enable: false
    interval: 30
    cluster: ceph
    command: /usr/bin/ceph
    scripts:
      - ceph_orch.py

  ceph_rgw:
    enable: false
    interval: 60
    cluster: ceph
    max_workers: 8
    limit_bucket: 10000
    reshard_threshold: 200000
    scripts:
      - ceph_rgw.py

  ceph_pool_osd_mapping:
    enable: true
    interval: 300
    cluster: ceph
    command: /usr/bin/ceph
    scripts:
      - ceph_pool_osd_mapping.py

  ceph_rbd:
    enable: true
    interval: 300
    ceph_conf: /etc/ceph/ceph.conf
    keyring: /etc/ceph/ceph.client.admin.keyring
    rbd_user: admin
    pools:
      - rbd
    scripts:
      - ceph_rbd.py